<?php

namespace Database\Seeders;

use App\Models\ConfigAttribute;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class ConfigAttributesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('config_attributes')->delete();
        $attributes=[
            [
                'attribute_name'=>'level_location',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],
            [
                'attribute_name'=>'levels_count',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'levels_count',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'water_source',
                'rules'=>['string','in:well,pipe'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'permissible_construction_ratio',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>4
            ],
            [
                'attribute_name'=>'number_of_floors_that_can_be_built',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>6
            ],
            [
                'attribute_name'=>'permissible_construction_ratio',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>6
            ],
            [
                'attribute_name'=>'soil_type',
                'rules'=>['string','in:clay,sandy'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>7
            ],
            [
                'attribute_name'=>'water_source',
                'rules'=>['string','in:well,rain'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>7
            ],
            [
                'attribute_name'=>'ceiling_height',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'number_of_shipping_doors',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'number_of_entries',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'number_of_exits',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>8
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>9
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>11
            ],
            [
                'attribute_name'=>'pledge_type_id',
                'rules'=>['exists:pledge_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'description',
                'rules'=>['string'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1
            ],
            [
                'attribute_name'=>'age',
                'rules'=>['numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1
            ],
            [
                'attribute_name'=>'map_points',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],

            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>8
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>8
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>8
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>9
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>9
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>9
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>10
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>11
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>11
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>11
            ],
            [
                'attribute_name'=>'rooms',
                'rules'=>['array'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'rooms.*.type_id',
                'rules'=>['required','numeric','exists:room_types,id'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'rooms.*.number',
                'rules'=>['required','numeric'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>12
            ],
            [
                'attribute_name'=>'property_condition',
                'rules'=>['string','in:i_live_in_it,empty,inhabited,rented,not_rented'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>1
            ],
            [
                'attribute_name'=>'property_condition',
                'rules'=>['string','in:i_live_in_it,empty,inhabited,rented,not_rented'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>2
            ],
            [
                'attribute_name'=>'property_condition',
                'rules'=>['string','in:i_live_in_it,empty,inhabited,rented,not_rented'],
                'is_required'=>true,
                'is_used_for_filtering'=>false,
                'classification_id'=>1,
                'category_id'=>3
            ],

        ];

        foreach ($attributes as $attribute)
        {
            ConfigAttribute::create([
                'attribute_name'=>$attribute['attribute_name'],
                'rules'=>json_encode($attribute['rules']),
                'is_required'=>$attribute['is_required'],
                'is_used_for_filtering'=>$attribute['is_used_for_filtering'],
                'classification_id'=>$attribute['classification_id'],
                'category_id'=>array_key_exists('category_id',$attribute)?$attribute['category_id']:null,
            ]);
        }
    }
}
